@ClotheoAPI.Presentation_HostAddress = https://localhost:7089
@tokenAdmin = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIxIiwidW5pcXVlX25hbWUiOiJhZG1pbiIsImVtYWlsIjoiYWRtaW5AZXhhbXBsZS5jb20iLCJyb2xlIjoiQWRtaW4iLCJuYmYiOjE3NDY1MzA2MTAsImV4cCI6MTc0Njc0NjYxMCwiaWF0IjoxNzQ2NTMwNjEwLCJpc3MiOiJDbG90aGVvQVBJIiwiYXVkIjoiQ2xvdGhlb0Zyb250ZW5kIn0.Yg5i2vlBsnIXMj2gpdSgBcWFS1fAH48cuJyGopvi_tM
@tokenUser = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1laWQiOiIyIiwidW5pcXVlX25hbWUiOiJ1c2VyIiwiZW1haWwiOiJ1c2VyQGV4YW1wbGUuY29tIiwicm9sZSI6IlVzZXIiLCJuYmYiOjE3NDY1MjkyMjcsImV4cCI6MTc0Njc0NTIyNywiaWF0IjoxNzQ2NTI5MjI3LCJpc3MiOiJDbG90aGVvQVBJIiwiYXVkIjoiQ2xvdGhlb0Zyb250ZW5kIn0.-F60SuzkQI-cooOnz4G6CJMhSo3RBnNw9hLUYAF8yn4

POST {{ClotheoAPI.Presentation_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@example.com",
  "password": "admin"
}

###

POST {{ClotheoAPI.Presentation_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "user@example.com",
  "password": "user"
}

###

POST {{ClotheoAPI.Presentation_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "username": "user",
  "email": "user@example.com",
  "password": "user",
  "profilePicture": ""
}

###

GET {{ClotheoAPI.Presentation_HostAddress}}/api/category

###

POST {{ClotheoAPI.Presentation_HostAddress}}/api/category
Content-Type: application/json
Authorization: Bearer {{tokenAdmin}}

{
  "name": "koZ"
}

###

@id = 100
DELETE {{ClotheoAPI.Presentation_HostAddress}}/api/category/{{id}}
Authorization: Bearer {{tokenAdmin}}

###

GET {{ClotheoAPI.Presentation_HostAddress}}/api/category/{{id}}

###

GET {{ClotheoAPI.Presentation_HostAddress}}/api/user
Authorization: Bearer {{token}}

###

DELETE {{ClotheoAPI.Presentation_HostAddress}}/api/user/{{id}}

###

GET {{ClotheoAPI.Presentation_HostAddress}}/api/user/{{id}}

###

PUT {{ClotheoAPI.Presentation_HostAddress}}/api/user/{{id}}
Content-Type: application/json

{
  "username": "string",
  "password": "string",
  "profilePicture": "string"
}

###
